-- MySQL Script generated by MySQL Workbench
-- Mon Feb  5 18:36:09 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema shopping_china
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema shopping_china
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shopping_china` DEFAULT CHARACTER SET utf8 ;
USE `shopping_china` ;

-- -----------------------------------------------------
-- Table `shopping_china`.`contato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopping_china`.`contato` (
  `idcontato` INT NOT NULL AUTO_INCREMENT,
  `contato` VARCHAR(50) NULL,
  `rede_social` VARCHAR(45) NULL,
  PRIMARY KEY (`idcontato`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopping_china`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopping_china`.`produto` (
  `idproduto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NULL,
  `descricao` TEXT(300) NULL,
  `preco` DECIMAL(18,2) NULL,
  PRIMARY KEY (`idproduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopping_china`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopping_china`.`cliente` (
  `cpf` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `compras` VARCHAR(60) NULL,
  `promocao` VARCHAR(45) NULL,
  `contato_idcontato` INT NOT NULL,
  `produto_idproduto` INT NOT NULL,
  PRIMARY KEY (`cpf`, `contato_idcontato`, `produto_idproduto`),
  INDEX `fk_cliente_contato1_idx` (`contato_idcontato` ASC),
  INDEX `fk_cliente_produto1_idx` (`produto_idproduto` ASC),
  CONSTRAINT `fk_cliente_contato1`
    FOREIGN KEY (`contato_idcontato`)
    REFERENCES `shopping_china`.`contato` (`idcontato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_produto1`
    FOREIGN KEY (`produto_idproduto`)
    REFERENCES `shopping_china`.`produto` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopping_china`.`shopping_china`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopping_china`.`shopping_china` (
  `cnpj` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `razao_social` VARCHAR(45) NULL,
  `seguimento` VARCHAR(45) NULL,
  `contato_idcontato` INT NOT NULL,
  `cliente_cpf` INT NOT NULL,
  PRIMARY KEY (`cnpj`, `contato_idcontato`, `cliente_cpf`),
  INDEX `fk_shopping_china_contato1_idx` (`contato_idcontato` ASC),
  INDEX `fk_shopping_china_cliente1_idx` (`cliente_cpf` ASC),
  CONSTRAINT `fk_shopping_china_contato1`
    FOREIGN KEY (`contato_idcontato`)
    REFERENCES `shopping_china`.`contato` (`idcontato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_shopping_china_cliente1`
    FOREIGN KEY (`cliente_cpf`)
    REFERENCES `shopping_china`.`cliente` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopping_china`.`shopping_china_has_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopping_china`.`shopping_china_has_produto` (
  `shopping_china_cnpj` INT NOT NULL,
  `produto_idproduto` INT NOT NULL,
  PRIMARY KEY (`shopping_china_cnpj`, `produto_idproduto`),
  INDEX `fk_shopping_china_has_produto_produto1_idx` (`produto_idproduto` ASC),
  INDEX `fk_shopping_china_has_produto_shopping_china_idx` (`shopping_china_cnpj` ASC),
  CONSTRAINT `fk_shopping_china_has_produto_shopping_china`
    FOREIGN KEY (`shopping_china_cnpj`)
    REFERENCES `shopping_china`.`shopping_china` (`cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_shopping_china_has_produto_produto1`
    FOREIGN KEY (`produto_idproduto`)
    REFERENCES `shopping_china`.`produto` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

use shopping_china;
